### PR TITLE
Menu icons changed

### PR DESCRIPTION
**Pull request by stuartbreckenridge**
Uses more appropriate icons for the menus introduced in #2774

### CODE REVIEW

**Comment by stuartbreckenridge** [comment]
The above changes result in this:

Screenshot 2021-02-23 at 21 57 28

**Comment by vincode-io** [comment]
Can we put these in the same order as the Mac menu without the separator? It will keep the two applications more consistent.

**Comment by vincode-io** [comment]
We should probably make this change on `ios-candidate`.

**Comment by stuartbreckenridge** [comment]
Created a separate PR for this #2829 on `ios-candidate`.

**Pull request closed without merging**
