### PR TITLE
Logging changes

### PR DESCRIPTION
**Pull request by stuartbreckenridge**
For review; related to #3637 

- Adds `Logging` protocol
- Moves to Swift-style `OSLog` usage

### CODE REVIEW

**Comment by vincode-io** [comment]
That Logging protocol looks generally, very useful. Maybe we should put it in RSCore?

**Comment by stuartbreckenridge** [comment]
I thought about it but didn't have enough time to check if any of the extension targets required `Logging` but not `RSCore`.

**Comment by vincode-io** [comment]
Let's go ahead and put `Logging` in `RSCore` and add `RSCore` to any extensions that need `Logging`, but don't have `RSCore`. Take your time. We have a lot of other things to do to get 6.2 ready for release.

**Comment by vincode-io** [comment]
Since this fix is scheduled to go into 6.1.1 we will need to merge it into `mac-release` and then into `ios-release` after iOS 6.1 is released.

**Comment by stuartbreckenridge** [comment]
Removing `os_log` are replacing with `Logger` via the `Logging` protocol is complete for everything bar a few classes that conform to `CloudKitZone`, which can be tidied up later.

**Comment by vincode-io** [comment]
@stuartbreckenridge Is there any reason that you didn't change the classes conforming to `CloudKitZone`? Did you just run out of steam or was there some technical reason?

**Comment by stuartbreckenridge** [comment]
It needs a commit to RSCore before the final work can be done in the app.

**Comment by vincode-io** [comment]
Ok. If that isn't something you can get to, I can take a look.

**Comment by stuartbreckenridge** [comment]
@vincode-io  There are no more `os_log` entries.

**Comment by vincode-io** [comment]
@stuartbreckenridge Thanks! I just saw that and was about to merge it.

**Pull request merged**
