### PR TITLE
Mac Preferences

### LINKED ISSUE #2177: Implement macOS Settings Toolbar using the Toolbar
We want to look as native as possible so we should try to make the settings toolbar selection look as much like Mail's, Safari's, etc...

### PR DESCRIPTION
**Pull request by stuartbreckenridge**
- Matches production for #2179 (appearance is still pending)
- WiP For #2180:
    - deleting accounts is supported
    - add Local, Feedbin, and others are supported
    - updating accounts (e.g. credentials, names) is still pending
- Largely fixes #2177 
    - button highlighting doesn't cover the entire button

### CODE REVIEW

**Comment by stuartbreckenridge** [comment]
• Fixes #2177 & Fixes #2179 (plus appearance)
• #2180: Adding, editing, and deleting Accounts is supported for most accounts

Note: the add account sheet includes all accounts, so an _Add Account_ option could be used on the + on the main tool bar.

**Comment by stuartbreckenridge** [comment]
Screenshot 2020-07-15 at 9 16 03 AM
Screenshot 2020-07-15 at 9 16 07 AM
Screenshot 2020-07-15 at 9 16 14 AM
Screenshot 2020-07-15 at 9 16 29 AM
Screenshot 2020-07-15 at 9 16 48 AM
Screenshot 2020-07-15 at 9 19 17 AM

**Comment by stuartbreckenridge** [comment]
Fixes #2177 
Fixes #2179 
Fixes #2180

**Comment by vincode-io** [comment]
Did you intend to change `Mac/Base.lproj/Preferences.storyboard`?

**Comment by stuartbreckenridge** [comment]
No. I literally opened it up to look at the layout.

**Comment by stuartbreckenridge** [comment]
@vincode-io I restored the storyboard to the previous version in the commit history before I started working on the feature.

**Pull request merged**
