### PR TITLE
Add Accounts UI Refresh

### PR DESCRIPTION
**Pull request by stuartbreckenridge**
• An extenison has been added to `AccountType` for iconColors (which have been added to the asset catalogs) and localised account names. SPM can handle resources so it might make sense to move to the `Account` package in the future. 

• Add Account screen now has sections for local, icloud, web, and self-hosted, icons are now tinted and sized a bit smaller, and text is now `body` sized.

Simulator Screen Shot - iPhone 12 Pro Max - 2020-10-27 at 11 37 08
Simulator Screen Shot - iPhone 12 Pro Max - 2020-10-27 at 11 45 05

### CODE REVIEW

**Comment by stuartbreckenridge** [comment]
IMG_0069

**Comment by benubois** [comment]
@stuartbreckenridge This looks great!

One thing though: Feedbin's brand color should be black. The blue is more of an accent color. There's a version of the logo designed to work on either a light or dark background that might be a good fit here (though it might not be a good template image).

[feedbin-logo-filled.pdf](https://github.com/Ranchero-Software/NetNewsWire/files/5445761/feedbin-logo-filled.pdf)

Happy to submit a separate pull request if you're done working on this.

Thanks!

Frame 36

**Comment by stuartbreckenridge** [comment]
@benubois I switched the Feedbin PDFs in 83a3a03.

Simulator Screen Shot - iPhone 12 Pro Max - 2020-10-27 at 22 08 02
Simulator Screen Shot - iPhone 12 Pro Max - 2020-10-27 at 22 08 08

**Comment by benubois** [comment]
Really appreciate it!

**Pull request merged**
