### PR TITLE
Solve codesign & library embedding for Share Extension on Xcode 12.5

### PR DESCRIPTION
**Pull request by GetToSet**
A codesign issue appears on clean build with Xcode 12.5. #3031

Screenshot 2021-05-23 AM 9 21 44

Seems that RSCore was copied into wrong location, and adding a `--deep` (#3032) is not the ideal solution.

Screenshot 2021-05-23 AM 9 33 51

I found that RSCore should be an explicit dependency of SyncDatabase, which is [imported](https://github.com/Ranchero-Software/NetNewsWire/blob/7558120dc39004e9d57e02c3e36c20fb4223358b/SyncDatabase/Sources/SyncDatabase/SyncDatabase.swift#L10) in related code.

This pull request adds RSCore as an explicit dependency of SyncDatabase to solve codesign issue on Xcode 12.5.

### CODE REVIEW

**Comment by stuartbreckenridge** [comment]
The only problem I see with this solution is that the Share Extension is ~10x the size it was before:

Screenshot 2021-05-23 at 21 46 27

**Comment by GetToSet** [comment]
> The only problem I see with this solution—though I doubt adding this dependency is the culprit—is that the Share Extension is ~10x the size it was before. (This appears to be an Xcode 12.5 problem in the way it is determining where frameworks should go.)
> 
> Screenshot 2021-05-23 at 21 46 27

I'll install a previous version of Xcode and take a deeper investigation to see what's actually changed.

**Comment by stuartbreckenridge** [comment]
There are two regressions I've identified in Xcode 12.5:
- The first, as you've got in your [screenshot](https://user-images.githubusercontent.com/8158163/119262692-acd2eb00-bc0e-11eb-8857-49f728bfc4e5.png), is that the Sparkle framework is copied _after_ the Code Sign Sparkle Run Script. As a result, the script can't remove unneeded components because they are not in the location expected. In Xcode 12.4 and earlier, that ordering is reversed, i.e. Copy then Script, and it allows the Run Script to remove unneeded components after to the Copy.
- Xcode 12.5, with our current Package configuration, embeds all the Frameworks in the Share Extension. (Hence the ballooning in size!)

**Comment by GetToSet** [comment]
For Xcode 12.4: 
* Dynamic library decencies of 'Account', which NetNewsWire Share Extension relies on, won't be copied into bundle when it's not listed in 'Embed Frameworks'.
* Linking against 'RSCore' automatically adds it into 'Embed Frameworks', and removing it also removes it from linking phase. It seems a Xcode bug, 'RSCore' has to be bundled though it's not needed and therefore a script was needed to remove RSCore from the final bundle.

https://user-images.githubusercontent.com/8158163/119300228-febd5480-bc92-11eb-9b68-ea857243df23.mov

For Xcode 12.5:
* Removing 'RSCore' in 'Embed Frameworks' won't remove it from being linked, therefore the deletion script is not needed any more. (The first commit, it's backwards compatible with Xcode 12.4)
* Swift Package Manager 5.4 in Xcode 12.5 seems to have new behavior, which forces copy and sign dynamic frameworks that 'Account' relies on even they're not included in 'Embed Frameworks', in a very late process, even after cleanup script runs. Possibly related to [this](https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-release-notes#Swift-Packages).

Screenshot 2021-05-24 AM 10 55 40

* Moving cleanup script into the main app build phase should be the simplest way to solve this problem, which is what the second commit did.

**Comment by GetToSet** [comment]
For issues related with Sparkle on Xcode 12.5, maybe i'll open another PR for this.

**Comment by vincode-io** [comment]
@GetToSet What's the status of this pull request given that we are currently staying on Xcode 12.4 for development. Does it have any net benefit?

**Comment by GetToSet** [comment]
> @GetToSet What's the status of this pull request given that we are currently staying on Xcode 12.4 for development. Does it have any net benefit?

Initially I found the project won't build on Xcode 12.5 and try to fix it. There's no need for this PR if only Xcode 12.4 is targeted.

**Comment by vincode-io** [comment]
@GetToSet I've tested this pull request and want to merge it. Could you please resolve the merge conflicts so that I can?

**Comment by GetToSet** [comment]
> @GetToSet I've tested this pull request and want to merge it. Could you please resolve the merge conflicts so that I can?

Seems this PR has already been merged.

**Pull request closed without merging**
