### PR TITLE
Read mark interval setting

### PR DESCRIPTION
**Pull request by emoonadev**
Added a mark read option to setting screen.
The feature was requested https://github.com/Ranchero-Software/NetNewsWire/issues/3743 and I think that is a good feature.

Screenshot 2022-11-15 at 15 51 09

### CODE REVIEW

**Comment by vincode-io** [comment]
@emoonadev Please read our [Contributing](https://github.com/Ranchero-Software/NetNewsWire/blob/main/CONTRIBUTING.md) document about how to get a new feature included in NetNewsWire. We're very careful about adding new features and actively work to avoid feature bloat. All new features require @brentsimmons' approval before adding and the procedure for making that happen is in the Contributing document.

**Comment by emoonadev** [comment]
Oh you're right. Ok so this feature is no relevant?

**Comment by vincode-io** [comment]
I don't know. Did you get @brentsimmons approval?

**Comment by brentsimmons** [comment]
I hate to disappoint, but I don’t want to add this feature. In my 20 years of doing NetNewsWire, it’s one of the least-often-requested features, so much so that I don’t think it’s worth the cost of adding a setting for it.

**Pull request closed without merging**
