### PR TITLE
Bugfix progress indicator max width

### PR DESCRIPTION
**Pull request by mvolpato**
#1836 
The bug was caused by activating/deactivating the progress bar width constraint.

Setting and modifying constraints from storyboard is totally new to me. I learned new stuff while working on this. 

This should be merged for v5.0.1

### CODE REVIEW

**Comment by vincode-io** [comment]
@mvolpato Could you retarget this pull request to the new mac-release branch where we will be doing the work for 5.0.1?  Thanks!

**Comment by vincode-io** [comment]
@mvolpato Could you retarget this pull request to the new mac-release branch where we will be doing the work for 5.0.1?  Thanks!

**Comment by mvolpato** [comment]
> @mvolpato Could you retarget this pull request to the new mac-release branch where we will be doing the work for 5.0.1? Thanks!

Should I move it to `ios-release` or `ios-candidate` instead?

**Comment by vincode-io** [comment]
So sorry for the confusion. It should be the ios-release branch.

**Pull request merged**
