### PR TITLE
Changes to NewsBlur refreshAll process

### PR DESCRIPTION
**Pull request by quanganhdo**
Resolves https://github.com/Ranchero-Software/NetNewsWire/issues/2617
Related conversation: https://netnewswire.slack.com/archives/CCGTPJDPD/p1605910165150500

WIP.

### CODE REVIEW

**Comment by vincode-io** [comment]
@quanganhdo Do we need to leave this as a WIP for some reason?

**Comment by quanganhdo** [comment]
The missing part is related to the issue you raised in the Slack thread (the current code not being able to download read articles).

**Comment by vincode-io** [comment]
I don't think we will be able to handle it.  It just looks like a deficiency in the NewsBlur API.  All the syncing services are a little bit different.  This is just something we'll have to live with.  It won't impact our unread counts or starred articles, so it isn't the end of the world.

**Comment by vincode-io** [comment]
It is ok for us to move forward without being able to download unread articles, so let's just go ahead with this pull request.

**Pull request merged**
