### PR TITLE
Adds sidebar toggles for notifications/reader

### LINKED ISSUE #2674: Feature: Add 'Get Info' to a Feed's Context Menu in NNW 6
It's currently only available using `⌘+I` or the `Window -> Info` menu.

### PR DESCRIPTION
**Pull request by stuartbreckenridge**
Fixes #2674 by surfacing context menu options for Notifications/Reader View.

### CODE REVIEW

**Review by brentsimmons — CHANGES_REQUESTED** [review]
Let’s use a checkmark next to the menu items.

Language should match the inspector window, but using menu item case:

Show Notifications for New Articles
Always Use Reader View

(With the standard checkmark on the left to specify whether they are on or off.)

**Comment by stuartbreckenridge** [comment]
@brentsimmons 

Checkmarks added in 62ed749.

It also posts a notification when webfeed preferences are updated from the context menu, which the Inspector observes, to keep the Inspector in sync.

**Comment by stuartbreckenridge** [comment]
https://user-images.githubusercontent.com/7046652/106543950-b7735280-6541-11eb-82bf-07360dea00e3.mov

**Comment by stuartbreckenridge** [comment]
Don't merge this just yet. I'm going to update it so that the sidebar check for notifications being authorised.

**Comment by stuartbreckenridge** [comment]
Fixed in aa0a5d2

**Pull request merged**
