### PR TITLE
Adds author name as a searchable field

### PR DESCRIPTION
**Pull request by banaslee**
Fixes https://github.com/Ranchero-Software/NetNewsWire/issues/1695

Users are now able to search for an author name and get as results, articles by authors with that name

Did this by adding an `authors` column to the `search` table and filling it correctly when building the text index
Database also migrates correctly when coming from a previous version by recreating the `search` table and the index

### CODE REVIEW

**Comment by vincode-io** [comment]
@banaslee Could you change this so that it doesn't do a full reindexing of the search table. @brentsimmons feels it would be better to just index the author field for new and updated articles.

**Comment by banaslee** [comment]
Sure @vincode-io. That should be a very small change. Do you have a suggestion on how to reliably test updated articles case?

**Comment by vincode-io** [comment]
As new articles come in, they should be able to be found in the search function when searching for an authors name. I would start with a new local account and subscribe to the Washington Posts feeds. Then as articles come in, search for them by author name.

**Comment by banaslee** [comment]
Ok @vincode-io, it's more complex than I expected...

See, it's not possible to just add a column to a virtual table like a fts4 table. So, on an upgrade scenario, we need to recreate the table in order to add the column. By recreating it, we lose its contents unless we reindex...

Let me share what I was trying to do:
I was going to delete the code that sets `SearchRowID` to null for all the articles. I was doing this to force a rebuild of the index. Though, what I found in my tests, is if I don't do it, the values in `SearchRowID` become outdated and search stops working.

Any ideas?

I guess the slowness you experienced happens when there's a huge number of articles in the database. Right? As I'm running the app with the default feeds, I'm not running into that problem.

**Comment by brentsimmons** [comment]
Instead of adding a field, how about just appending the author name as text to the body in the search table?

**Comment by banaslee** [comment]
Ah @brentsimmons! Thanks, forgot about that (I had entertained that idea in Slack but dropped it). 

What are your thoughts on `body` now including more than the body?

**Comment by brentsimmons** [comment]
I don’t love it, but it seems like the pragmatic thing here, so it’s fine.

**Comment by vincode-io** [comment]
If we ever decided we wanted to target the author field in a search, we have the option then of reindexing everything. We don't have to do it right now.

**Comment by banaslee** [comment]
@vincode-io I didn't understand your comment: what's the difference between "target the author field in a search" and what we're doing here?

**Comment by vincode-io** [comment]
So that you could search for `author:Simmons` and only get article penned by people with the name Simmons, but not articles where Simmons is mentioned. AppKit and UIKit have ways of turning that `author:` portion into a token with a special user interface.

**Comment by banaslee** [comment]
Got it. If I take @brentsimmons suggestion I'm not sure that will be possible. But is always possible to go back and add an `authors` column like I initially did.
I'm now trying @brentsimmons suggestion 🤞

**Comment by banaslee** [comment]
New PR at https://github.com/Ranchero-Software/NetNewsWire/pull/2804

**Pull request merged**
